### ISSUE TITLE
Uncaught exception 'CurlException'

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-campaign-monitor#8]
From a customer:

```
Fatal error: Uncaught exception 'CurlException' with message 'Error making request with curl_error: Operation timed out after 10001 milliseconds with 0 bytes received' in wp-content/plugins/restrict-content-pro-campaign-monitor/vendor/class/transport.php:174
Stack trace:
#0 wp-content/plugins/restrict-content-pro-campaign-monitor/vendor/class/base_classes.php(291): CS_REST_CurlTransport->make_call(Array)
#1 wp-content/plugins/restrict-content-pro-campaign-monitor/vendor/class/base_classes.php(234): CS_REST_Wrapper_Base->_call(Array, 'GET', 'https://api.cre...')
#2 wp-content/plugins/restrict-content-pro-campaign-monitor/vendor/csrest_clients.php(145): CS_REST_Wrapper_Base->get_request('https://api.cre...')
#3 wp-content/plugins/restrict-content-pro-campaign-monitor/rcp-campaign-monitor.php(207): CS_REST_Clients->get in wp-content/plugins/restrict-content-pro-campaign-monitor/vendor/class/transport.php on line 174
```

Looks like the Campaign Monitor library is throwing an exception but it's not being caught anywhere.

**Comment by nosegraze** [comment]
PR: #9
